[versions]
bstats = "3.0.2"
adventure = "4.15.0"

[libraries]
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

# Platforms
platform-paper = { module = "io.papermc.paper:paper-api", version = "1.20.4-R0.1-SNAPSHOT" }

# Webhook clients
client-discord = { module = "io.github.4drian3d:jdwebhooks", version = "1.0.1" }

# Libraries
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
miniplaceholders = { module = "io.github.miniplaceholders:miniplaceholders-api", version = "2.2.3" }

dazzleconf = { module = "space.arim.dazzleconf:dazzleconf-ext-snakeyaml", version = "1.3.0-M2" }
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.9" }
snakeyaml = { module = "org.yaml:snakeyaml", version = "2.2" }
mcdiscordserializer = { module = "dev.vankka:mcdiscordreserializer", version = "4.3.0" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
spotless = { id = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.18.0" }
pluginYml = { id = "net.minecrell.plugin-yml.bukkit", version = "0.5.3" }