[versions]
adventure = "4.20.0"
bstats = "3.0.2"
cloud-minecraft = "2.0.0-beta.14"

[libraries]
platform-paper = { module = "io.papermc.paper:paper-api", version = "1.21.4-R0.1-SNAPSHOT" }
platform-sponge = { module = "org.spongepowered:spongeapi", version = "10.0.0" }

adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text-serializer-ansi = { module = "net.kyori:adventure-text-serializer-ansi", version.ref = "adventure" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }

bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
bstats-sponge = { module = "org.bstats:bstats-sponge", version.ref = "bstats" }

cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-minecraft" }
cloud-sponge = { module = "org.incendo:cloud-sponge7", version.ref = "cloud-minecraft" }
cloud-minecraftExtras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloud-minecraft" }

configurate = { module = "org.spongepowered:configurate-yaml", version = "4.2.0" }
jdwebhooks = { module = "io.github.4drian3d:jdwebhooks", version = "1.1.0" }
mcdiscordserializer = { module = "dev.vankka:mcdiscordreserializer", version = "4.4.0-SNAPSHOT" }
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.11" }

plugin-carbon = { module = "de.hexaoxi:carbonchat-api", version = "3.0.0-beta.26" }
plugin-miniplaceholders = { module = "io.github.miniplaceholders:miniplaceholders-api", version = "3.0.1" }

[plugins]
resourceFactory-paper = { id = "xyz.jpenilla.resource-factory-paper-convention", version = "1.2.1" }
sponge = { id = "org.spongepowered.gradle.plugin", version = "2.2.0" }
runPaper = { id = "xyz.jpenilla.run-paper", version = "2.3.0" }